name: e_note_khadem
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.7+7

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.3
  bloc: ^7.2.1
  flutter_bloc: ^7.3.1
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  pull_to_refresh: ^2.0.0
  double_back_to_close_app: ^2.1.0
  conditional_builder_null_safety: ^0.0.6
  font_awesome_flutter: ^10.4.0
  scan: ^1.6.0
  images_picker: ^1.2.11
  google_fonts: any
  flutter_switch: ^0.3.2
  loading_animation_widget: ^1.2.0+4
  intl: ^0.18.1
  nanoid: ^1.0.0
  flutter_launcher_icons: ^0.13.1
  firebase_storage: ^11.2.4
  file_picker: ^5.3.2
  open_file: ^3.3.2
  permission_handler: ^10.4.2
  qr_flutter: ^4.1.0
  url_launcher: ^6.1.12
  dropdown_button2: ^2.3.7
  firebase_crashlytics: ^3.3.4
  firebase_performance: ^0.9.2+4
  syncfusion_flutter_datepicker: ^22.2.11
  firebase_messaging: ^14.6.8
  flutter_local_notifications: ^15.1.1
  email_otp: ^2.0.1
  qr_code_scanner: ^1.0.1
  path_provider: ^2.1.1
  syncfusion_flutter_xlsio: ^22.2.12
  floating_snackbar: ^1.0.3+1
  upgrader: ^9.0.0
  firebase_app_check: ^0.2.1+13






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - fonts/cairoFont/Cairo-Black.ttf


  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/cairoFont/Cairo-Black.ttf
        - asset: fonts/cairoFont/Cairo-Bold.ttf
        - asset: fonts/cairoFont/Cairo-ExtraLight.ttf
        - asset: fonts/cairoFont/Cairo-Light.ttf
        - asset: fonts/cairoFont/Cairo-Regular.ttf
        - asset: fonts/cairoFont/Cairo-SemiBold.ttf